export const USERS_FETCH_REQUESTED = 'USERS_FETCH_REQUESTED';
export const USERS_FETCH_SUCCEEDED = 'USERS_FETCH_SUCCEEDED';
export const USERS_FETCH_FAILED = 'USERS_FETCH_FAILED';

export const USER_CREATE_REQUESTED = 'USER_CREATE_REQUESTED';
export const USER_CREATE_SUCCEEDED = 'USER_CREATE_SUCCEEDED';
export const USER_CREATE_FAILED = 'USER_CREATE_FAILED';

export const IS_FETCHING = 'IS_FETCHING';
